""" BASELINE SETTINGS
set nocompatible
syntax on

" set tab indent to 4 spaces
set is 
set smartindent
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab

" allow all backspaces within insert mode
set bs=2

" dsiplay line number, and cursor position
set ruler
set number
set numberwidth=3

set visualbell

" confirm save upon exitiing w/o saving changes
set confirm

" search
"set ignorecase
set smartcase
set incsearch

set cursorline
set colorcolumn=80
set nowrap

" backups/undo
set nobackup
set undodir=~/.vim/undodir
set undofile

set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=*/bin/*,*/build/*

""" PLUGINS
call plug#begin()

Plug 'morhetz/gruvbox'
Plug 'tpope/vim-fugitive'
Plug 'jremmen/vim-ripgrep'
Plug 'vim-utils/vim-man'
Plug 'lyuts/vim-rtags'
Plug 'ctrlpvim/ctrlp.vim'
"Plug 'Valloric/YouCompleteMe'
Plug 'mbbill/undotree'

call plug#end()

colorscheme gruvbox
set background=dark

if executable('rg')
    let g:rg_derive_root='true'
endif

""" MAPPINGS
" key mappings
let mapleader = " "

nmap <S-space> i
imap jj <Esc>
nmap :Q :q
nmap ss :w<CR>
nmap ff gt
nmap aa gT
nmap <C-h> gT
nmap <C-l> gt

nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>

nnoremap <leader>u :UndotreeShow<CR>
"pv - project view
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>
"ps - project search
nnoremap <leader>ps :Rg<SPACE>

"nnoremap <silent> <leader>gd :YcmCompleter GoTo<CR>
"nnoremap <silent> <leader>gf :YcmCompleter FixIt<CR>
